
import sys

message = sys.stdin.read().strip()

translations = {
    "Fix: Obscure WebDAV password and suppress rclone errors": "fix: 隐藏 WebDAV 密码并抑制 rclone 错误",
    "refactor: replace WebSocket with AJAX polling for status updates": "refactor: 使用 AJAX 轮询代替 WebSocket 进行状态更新",
    "fix: correct real-time log display": "fix: 修正实时日志的显示",
    "refactor: separate gofile.io upload logic into a module": "refactor: 将 gofile.io 上传逻辑拆分为独立模块",
    "fix: improve websocket real-time logging": "fix: 改进 WebSocket 的实时日志记录",
    "feat: display total log line count": "feat: 显示日志总行数",
    "feat: add line numbers and word wrap to log view": "feat: 为日志视图添加行号和自动换行功能",
    "feat: implement real-time logging with websockets": "feat: 使用 WebSocket 实现实时日志记录",
    "Add files via upload": "chore: 通过文件上传功能添加",
    "Fix modal UI for better mobile display and UX": "fix: 优化模态框界面，提升移动端显示效果和用户体验",
    "Implement security enhancements: Add robots.txt, improve auth, and add web modal prompt": "feat: 实施安全增强：添加 robots.txt，改进身份验证，并增加网页模态框提示",
    "chore: Add gofile_auth_test.py to .gitignore": "chore: 将 gofile_auth_test.py 添加到 .gitignore",
    "fix: Use generic endpoint for Gofile authenticated uploads": "fix: 为 Gofile 认证上传使用通用 API 端点",
    "chore: Add .gitignore to exclude test files": "chore: 添加 .gitignore 以排除测试文件",
    "feat: Add Gofile server-switching on upload failure": "feat: 增加 Gofile 上传失败时自动切换服务器的功能",
    "feat: Use default Gofile folder ID for authenticated uploads": "feat: 为需认证的上传操作使用默认 Gofile 文件夹 ID",
    "fix: Add Folder ID to Gofile uploads to fix authenticated uploads": "fix: 为 Gofile 上传添加文件夹 ID 以解决认证上传问题",
    "feat: Implemented pause/resume functionality for tasks and improved the task interface.": "feat: 实现任务的暂停/恢复功能并改进了任务界面",
    "docs: Update README files with new features and disclaimers": "docs: 更新 README 文件，包含新功能和免责声明",
    "feat: Implement user requests": "feat: 根据用户请求实现功能",
    "fix: Correctly serve blog assets": "fix: 修正博客静态资源的提供路径",
    "fix: Correct import for SessionMiddleware": "fix: 修正 SessionMiddleware 的导入语句",
    "ci: Disable cache in docker build action": "ci: 在 Docker 构建 Action 中禁用缓存",
    "fix: Explicitly set PYTHONPATH": "fix: 显式设置 PYTHONPATH 环境变量",
    "chore: Add debug commands to entrypoint": "chore: 在入口脚本中添加调试命令",
    "fix: Add missing dependencies": "fix: 补充缺失的依赖项",
    "feat: Serve blog at root and move downloader to /downloader": "feat: 在根路径提供博客，并将下载器移至 /downloader",
    "feat: Add user authentication": "feat: 添加用户身份验证功能",
    "style: Refactor frontend pages and optimize Docker entrypoint": "style: 重构前端页面并优化 Docker 入口脚本",
    "feat: Remove 15-minute timeout for commands": "feat: 移除命令执行的 15 分钟超时限制",
    "Remove 15-minute timeout mechanism": "chore: 移除 15 分钟超时机制",
    "feat: Implement advanced user-facing features": "feat: 实现面向用户的高级功能",
    "feat: Add i18n support and Chinese README": "feat: 添加国际化支持和中文 README",
    "feat: Add automatic directory cleanup": "feat: 添加自动目录清理功能",
    "feat: Improve archive naming and compression": "feat: 改进归档文件的命名和压缩",
    "fix: Correctly parse gofile.io API response": "fix: 修正 gofile.io API 响应的解析",
    "fix: Log gofile.io API response": "fix: 记录 gofile.io API 响应",
    "fix: Use correct arguments for kemono-dl": "fix: 为 kemono-dl 使用正确的命令行参数",
    "fix: Copy executables from builder stage": "fix: 从构建器阶段拷贝可执行文件",
    "fix: Upgrade to Python 3.11": "fix: 升级至 Python 3.11",
    "fix: Install git in builder stage": "fix: 在构建器阶段安装 git",
    "fix: Use multi-stage build to resolve dependency conflicts": "fix: 使用多阶段构建以解决依赖冲突",
    "fix: Resolve dependency conflicts with two-step install": "fix: 通过两步安装解决依赖冲突",
    "fix: Resolve dependency conflicts": "fix: 解决依赖冲突",
    "fix: Install kemono-dl from GitHub": "fix: 从 GitHub 安装 kemono-dl",
    "feat: Integrate kemono-dl downloader": "feat: 集成 kemono-dl 下载器",
    "feat: Implement aggressive proxy testing loop": "feat: 实现更积极的代理测试循环",
    "feat: Increase number of proxies to test": "feat: 增加待测试的代理数量",
    "feat: Implement concurrent proxy testing": "feat: 实现并发代理测试",
    "feat: Add auto-proxy feature and disclaimer": "feat: 添加自动代理功能及免责声明",
    "feat: Add proxy support for gallery-dl": "feat: 为 gallery-dl 添加代理支持",
    "fix: Remove extra quotes from gallery-dl command": "fix: 移除 gallery-dl 命令中的多余引号",
    "fix: Use correct flags for DeviantArt credentials": "fix: 为 DeviantArt 凭证使用正确的参数",
    "feat: Redesign log status page": "feat: 重新设计日志状态页面",
    "fix: Update gofile.io API endpoint": "fix: 更新 gofile.io API 端点",
    "refactor: Improve UI and fix credential leak": "refactor: 改进界面并修复凭证泄漏问题",
    "feat: Add DeviantArt API credential support": "feat: 添加 DeviantArt API 凭证支持",
    "fix: Implement real-time logging and timeout for commands": "fix: 实现命令的实时日志记录和超时",
    "feat: Add verbose logging to gallery-dl": "feat: 为 gallery-dl 添加详细日志记录",
    "fix: Handle single file downloads from gallery-dl": "fix: 处理 gallery-dl 单个文件的下载",
    "fix: Implement custom gofile.io upload": "fix: 实现自定义的 gofile.io 上传",
    "ci: Add step to check container status": "ci: 添加检查容器状态的步骤",
    "fix(ci): Hardcode lowercase repository name": "fix(ci): 硬编码小写的仓库名称",
    "fix(ci): Convert repository name to lowercase": "fix(ci): 将仓库名称转换为小写",
    "fix(ci): Correct image name in preview deployment": "fix(ci): 修正预览部署中的镜像名称",
    "fix(ci): Correctly reference Docker image in preview deployment": "fix(ci): 在预览部署中正确引用 Docker 镜像",
    "Revert \"refactor(ci): Remove preview deployment workflow\"": "revert: 撤销\"refactor(ci): 删除预览部署工作流\"",
    "refactor(ci): Remove preview deployment workflow": "refactor(ci): 删除预览部署工作流",
    "fix(ci): Use specific image tag in preview deployment": "fix(ci): 在预览部署中使用特定的镜像标签",
    "ci: Add preview deployment workflow": "ci: 添加预览部署工作流",
    "chore: Configure Dockerfile for Hugging Face Spaces": "chore: 为 Hugging Face Spaces 配置 Dockerfile",
    "feat: Add gofile.io upload and private mode": "feat: 添加 gofile.io 上传和私有模式",
    "docs: Update placeholders in README with actual repo info": "docs: 使用实际的仓库信息更新 README 中的占位符",
    "docs: Update README to Chinese": "docs: 将 README 更新为中文",
    "ci: Grant permissions to write packages": "ci: 授予写包的权限",
    "Initial project setup": "Initial project setup"
}

translated_message = translations.get(message, message)
print(translated_message)
