# .github/workflows/docker-publish.yml
name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      sha_tag: ${{ steps.meta.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/jyf0214/web-dl-manager
          tags: |
            type=sha,prefix=,format=short,key=version
            type=ref,event=branch

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          no-cache: true
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  preview-deployment:
    runs-on: ubuntu-latest
    needs: build_and_push
    if: github.event_name == 'push'
    steps:
      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run application for preview
        run: |
          docker run -d --name web-dl-manager \
            -p 5492:5492 \
            -p 127.0.0.1:6275:6275 \
            -e DATABASE_URL='sqlite:///:memory:' \
            -e TUNNEL_TOKEN=${{ secrets.TUNNEL_TOKEN }} \
            ghcr.io/jyf0214/web-dl-manager:${{ needs.build_and_push.outputs.sha_tag }}
          
          echo "Application is running in the background for preview."
          echo "It will be stopped automatically after the workflow finishes."
          sleep 300 # Wait for 5 minutes for testing purposes
